spring.application.name=WeatherApiService
server.port=8090

spring.datasource.url=jdbc:mysql://weatherforecastdb_seldomfish:9eb95afcb2830e99b3b0ff4bd05c094692e2e44a@d6lnl.h.filess.io:3307/weatherforecastdb_seldomfish
spring.datasource.username=root
spring.datasource.password=9eb95afcb2830e99b3b0ff4bd05c094692e2e44a
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

api.root=/api
api.location.root=${api.root}/locations
